apply plugin: 'com.android.application'

android {
    namespace 'com.benny.openlauncher'
    compileSdkVersion version_compileSdk
    buildToolsVersion version_buildTools

    defaultConfig {
        minSdkVersion version_minSdk
        targetSdkVersion version_compileSdk

        flavorDimensions "versionCode"
        multiDexEnabled false


        buildConfigField "boolean", "IS_TEST_BUILD", "false"
        buildConfigField "boolean", "IS_GPLAY_BUILD", "false"
        buildConfigField "String[]", "DETECTED_ANDROID_LOCALES", "${findUsedAndroidLocales()}"
        buildConfigField "String", "BUILD_DATE", "\"${getBuildDate()}\""
        buildConfigField "String", "GITHASH", "\"${getGitHash()}\""
        resValue "string", "manifest_package_id", "com.benny.openlauncher"

        resValue 'string', 'app_name', "OpenLauncher"

        applicationId "com.benny.openlauncher"
        versionCode 100
        versionName "1.0.0"
    }

    productFlavors {
        flavorDefault {
        }

        flavorGplay {
            buildConfigField "boolean", "IS_GPLAY_BUILD", "true"
        }

        flavorAtest {
          buildConfigField "boolean", "IS_NIGHTLY_BUILD", "true"
          versionCode = Integer.parseInt(new Date().format('yyMMdd'))
          versionName = new Date().format('yyMMdd')
          applicationId "com.benny.openlauncher.nightly"
          resValue 'string', 'app_name', "OL Nightly"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix ".debug"
        }
    }

    // No longer needed with AndroidX
    // configurations.all {
    //     resolutionStrategy {
    //         eachDependency { details ->
    //             if (details.requested.group == 'com.android.support') {
    //                 if (details.requested.name != 'multidex' && details.requested.name != 'multidex-instrumentation') {
    //                     details.useVersion "${version_library_appcompat}"
    //                 }
    //             }
    //         }
    //     }
    // }

    packaging {
        resources {
            excludes += ['META-INF/LICENSE-LGPL-2.1.txt', 'META-INF/LICENSE-LGPL-3.txt', 'META-INF/LICENSE-W3C-TEST']
        }
    }

    lint {
        disable 'MissingTranslation', 'InvalidPackage', 'ObsoleteLintCustomCheck', 'DefaultLocale', 'UnusedAttribute', 'VectorRaster', 'InflateParams', 'IconLocation', 'UnusedResources', 'TypographyEllipsis'
        abortOnError false
    }
}

dependencies {
    // AndroidX libraries
    implementation "androidx.recyclerview:recyclerview:${version_library_recyclerview}"
    implementation "androidx.appcompat:appcompat:${version_library_appcompat}"
    implementation "androidx.cardview:cardview:${version_library_cardview}"
    implementation "com.google.android.material:material:${version_library_design}"
    implementation "androidx.legacy:legacy-preference-v14:1.0.0"
    implementation "androidx.preference:preference:${version_library_preference}"
    implementation "androidx.constraintlayout:constraintlayout:${version_library_constraintlayout}"
    implementation 'com.jakewharton.threetenabp:threetenabp:1.4.6'

    // UI Libs
    implementation 'com.mikepenz:fastadapter:5.7.0'
    implementation 'com.mikepenz:fastadapter-extensions-binding:5.7.0'
    implementation 'jp.wasabeef:recyclerview-animators:4.0.2'
    implementation 'com.afollestad.material-dialogs:core:2.9.3'
    implementation 'agency.tango.android:material-intro-screen:0.0.5'
    implementation 'cat.ereza:customactivityoncrash:2.4.0'
    implementation 'de.psdev.licensesdialog:licensesdialog:2.2.0'
    implementation 'com.github.championswimmer:SimpleFingerGestures_Android_Library:1.2'
    implementation 'com.github.hedzr:FilePickerDialog:v0.11'
    implementation 'org.slf4j:slf4j-android:1.7.36'

    implementation ('com.github.ozodrukh:CircularReveal:2.0.1@aar') {
        transitive = true
    }

    implementation('com.github.turing-tech:MaterialScrollBar:13.3.4') {
        exclude group: 'com.android.support'
    }

    // Tools
    implementation "com.jakewharton:butterknife:${version_library_butterknife}"

    // Processors
    def anpros = ["com.jakewharton:butterknife-compiler:${version_library_butterknife}"]
    for (anpro in anpros) {
        annotationProcessor anpro
    }
}

repositories {
    mavenCentral()
}
