apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

def getUsedAndroidLocales() {
    def langs = new HashSet<String>()
    new File(project.projectDir, 'src/main/res').eachDir { dir ->
        def dirName = dir.name
        if (dirName.startsWith('values-')) {
            dir.eachFile { file ->
                if (file.name.endsWith(".xml")) {
                    if (file.getText('UTF-8').contains("<string")) {
                        langs.add('"' + dirName.replace("values-", "") + '"')
                        return
                    }
                }
            }
        }
    }
    return "new String[]{" + langs.join(',') + "}"
}

def getBuildDate() {
    return new Date().format('yyyy-MM-dd')
}

def getGitHash() {
    try {
        def proc = 'git rev-parse --short HEAD'.execute()
        proc.in.eachLine { line -> return line }
    } catch (e) {
        return "N/A"
    }
}

android {
    namespace 'com.jiadanni.launcher4d'
    compileSdkVersion version_compileSdk
    buildToolsVersion version_buildTools

    defaultConfig {
        minSdkVersion version_minSdk
        targetSdkVersion version_compileSdk

        flavorDimensions "versionCode"
        multiDexEnabled false


        buildConfigField "boolean", "IS_TEST_BUILD", "false"
        buildConfigField "boolean", "IS_GPLAY_BUILD", "false"
        buildConfigField "String[]", "DETECTED_ANDROID_LOCALES", getUsedAndroidLocales()
        buildConfigField "String", "BUILD_DATE", "\"${getBuildDate()}\""
        buildConfigField "String", "GITHASH", "\"${getGitHash()}\""
        resValue "string", "manifest_package_id", "com.jiadanni.launcher4d"

        resValue 'string', 'app_name', "OpenLauncher"

        applicationId "com.jiadanni.launcher4d"
        versionCode 100
        versionName "1.0.0"
    }

    productFlavors {
        flavorDefault {
        }

        flavorGplay {
            buildConfigField "boolean", "IS_GPLAY_BUILD", "true"
        }

        flavorAtest {
          buildConfigField "boolean", "IS_NIGHTLY_BUILD", "true"
          versionCode = Integer.parseInt(new Date().format('yyMMdd'))
          versionName = new Date().format('yyMMdd')
          applicationId "com.jiadanni.launcher4d.nightly"
          resValue 'string', 'app_name', "OL Nightly"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix ".debug"
        }
    }

    // No longer needed with AndroidX
    // configurations.all {
    //     resolutionStrategy {
    //         eachDependency { details ->
    //             if (details.requested.group == 'com.android.support') {
    //                 if (details.requested.name != 'multidex' && details.requested.name != 'multidex-instrumentation') {
    //                     details.useVersion "${version_library_appcompat}"
    //                 }
    //             }
    //         }
    //     }
    // }

    packaging {
        resources {
            excludes += ['META-INF/LICENSE-LGPL-2.1.txt', 'META-INF/LICENSE-LGPL-3.txt', 'META-INF/LICENSE-W3C-TEST']
        }
    }

    lint {
        disable 'InvalidPackage', 'ObsoleteLintCustomCheck', 'DefaultLocale', 'UnusedAttribute', 'VectorRaster', 'IconLocation', 'TypographyEllipsis'
        abortOnError false
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

dependencies {
    // Kotlin
    implementation "org.jetbrains.kotlin:kotlin-stdlib:${version_plugin_kotlin}"
    implementation "androidx.core:core-ktx:1.13.1"

    // AndroidX libraries
    implementation "androidx.recyclerview:recyclerview:${version_library_recyclerview}"
    implementation "androidx.appcompat:appcompat:${version_library_appcompat}"
    implementation "androidx.cardview:cardview:${version_library_cardview}"
    implementation "com.google.android.material:material:${version_library_design}"
    implementation "androidx.legacy:legacy-preference-v14:1.0.0"
    implementation "androidx.preference:preference:${version_library_preference}"
    implementation "androidx.constraintlayout:constraintlayout:${version_library_constraintlayout}"
    implementation 'com.jakewharton.threetenabp:threetenabp:1.4.6'

    // UI Libs
    implementation 'com.mikepenz:fastadapter:5.7.0'
    implementation 'com.mikepenz:fastadapter-extensions-binding:5.7.0'
    implementation 'jp.wasabeef:recyclerview-animators:4.0.2'


    implementation 'cat.ereza:customactivityoncrash:2.4.0'
    implementation 'de.psdev.licensesdialog:licensesdialog:2.2.0'


    implementation 'org.slf4j:slf4j-android:1.7.36'

    implementation('com.github.turing-tech:MaterialScrollBar:13.3.4') {
        exclude group: 'com.android.support'
    }

    // Tools
    implementation "com.jakewharton:butterknife:${version_library_butterknife}"

    // Processors
    def anpros = ["com.jakewharton:butterknife-compiler:${version_library_butterknife}"]
    for (anpro in anpros) {
        annotationProcessor anpro
    }
}

repositories {
    mavenCentral()
}